("Fiction", NULL),
("Biography", NULL),
("Business & Management", NULL),
("Children", NULL),
("Fiction", NULL),
("Film", NULL),
("Health", NULL),
("Non Fiction", NULL),
("Action & Adventure",1),
("Indian Fiction",1),
("Business",2),
("Politicians & Leaders",2),
("Economics",3),
("Human Resources",3),
("Classic Stories",4),
("Mystery & Thrillers",5),
("Movies",6),
("Child Care & Parenting",7),
("General",8),("Ancient",9),
("Current Affairs",9)